
// Copyright (c) 2018-2020, Pacific Biosciences of California, Inc.
//
// All rights reserved.
//
// THIS SOFTWARE CONSTITUTES AND EMBODIES PACIFIC BIOSCIENCES' CONFIDENTIAL
// AND PROPRIETARY INFORMATION.
//
// Disclosure, redistribution and use of this software is subject to the
// terms and conditions of the applicable written agreement(s) between you
// and Pacific Biosciences, where "you" refers to you or your company or
// organization, as applicable.  Any other disclosure, redistribution or
// use is prohibited.
//
// THIS SOFTWARE IS PROVIDED BY PACIFIC BIOSCIENCES AND ITS CONTRIBUTORS "AS
// IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
// THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
// PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL PACIFIC BIOSCIENCES OR ITS
// CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
// EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
// PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
// OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
// WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
// OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
// ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// File Description: A trained model generated programmatically using
// the primary-toolkit python package

/// This file is automatically generated by the CRF training scripts in
/// primary-toolkit (classifiers/CRF.py). Do not edit this file manually!

#include "ZOffsetCrfParams.h"

namespace PacBio {
namespace Primary {
namespace Postprimary {

constexpr std::array<float, 2> ZOffsetCrfModel::hswCurve;
constexpr std::array<std::array<float, 3>, 3> ZOffsetCrfModel::transitionScores;
constexpr float ZOffsetCrfModel::numFeatures;
constexpr std::array<std::array<float, 3>, 73> ZOffsetCrfModel::featureWeights;
constexpr std::array<std::tuple<CrfFeature, float, float>, 73> ZOffsetCrfModel::features;

}}} // PacBio::Primary::Postprimary
