This cram test uses experimental configurations that are likely to be changed or removed, once
the real preHQ algorithm is brought on line.  The whole test can probably be removed once
maintenance becomes annoying, as long as something else is dropped in its place

# This first test runs under 2^16 frames as the SpiderMetricBlock that is used for outputting to the BAZ file only supports numFrames as 16-bit. This means aggregating
# beyond 2^16 frames will results in an incorrect number of frames so we limit the current tests to less than that to validate the number of frames are correct from
# a metrics aggregation standpoint. The test below has the HQ-region all starting at the same time so that the preHQ metric block should be empty and all the subsequent
# metric blocks should be aggregated into one as the activity labels are all the same.
  $ BAZFILE=tmp.baz
  $ TRCFILE=/pbi/dept/primary/sim/mongo/test4_mongo_acgt_SNR-40.trc.h5
  $ smrt-basecaller --config source.TraceReplication='{"numFrames":57344, "numZmwLanes":4,"traceFile":"'$TRCFILE'" }' \
  > --config multipleBazFiles=false --config layout.lanesPerPool=1 --config=algorithm.modelEstimationMode=FixedEstimations  \
  > --outputbazfile ${BAZFILE} --config=prelimHQ.enablePreHQ=true --config=prelimHQ.hqThrottleFraction=1.0 > /dev/null

  $ bazviewer --silent -m -f ${BAZFILE}
  {
  \t"METRICS" :  (esc)
  \t[ (esc)
  \t\t{ (esc)
  \t\t\t"INTERNAL" : false, (esc)
  \t\t\t"METRICS" :  (esc)
  \t\t\t[ (esc)
  \t\t\t\t{ (esc)
  \t\t\t\t\t"BASELINE_MEAN" : 0, (esc)
  \t\t\t\t\t"BASELINE_SD" : 0, (esc)
  \t\t\t\t\t"BASE_WIDTH" : 0, (esc)
  \t\t\t\t\t"BPZVAR_A" : 0, (esc)
  \t\t\t\t\t"BPZVAR_C" : 0, (esc)
  \t\t\t\t\t"BPZVAR_G" : 0, (esc)
  \t\t\t\t\t"BPZVAR_T" : 0, (esc)
  \t\t\t\t\t"DME_STATUS" : 0, (esc)
  \t\t\t\t\t"ID" : 0, (esc)
  \t\t\t\t\t"NUM_BASES_A" : 0, (esc)
  \t\t\t\t\t"NUM_BASES_C" : 0, (esc)
  \t\t\t\t\t"NUM_BASES_G" : 0, (esc)
  \t\t\t\t\t"NUM_BASES_T" : 0, (esc)
  \t\t\t\t\t"NUM_FRAMES" : 0, (esc)
  \t\t\t\t\t"NUM_HALF_SANDWICHES" : 0, (esc)
  \t\t\t\t\t"NUM_PULSES" : 0, (esc)
  \t\t\t\t\t"NUM_PULSE_LABEL_STUTTERS" : 0, (esc)
  \t\t\t\t\t"NUM_SANDWICHES" : 0, (esc)
  \t\t\t\t\t"PIXEL_CHECKSUM" : 0, (esc)
  \t\t\t\t\t"PKMAX_A" : 0, (esc)
  \t\t\t\t\t"PKMAX_C" : 0, (esc)
  \t\t\t\t\t"PKMAX_G" : 0, (esc)
  \t\t\t\t\t"PKMAX_T" : 0, (esc)
  \t\t\t\t\t"PKMID_A" : 0, (esc)
  \t\t\t\t\t"PKMID_C" : 0, (esc)
  \t\t\t\t\t"PKMID_FRAMES_A" : 0, (esc)
  \t\t\t\t\t"PKMID_FRAMES_C" : 0, (esc)
  \t\t\t\t\t"PKMID_FRAMES_G" : 0, (esc)
  \t\t\t\t\t"PKMID_FRAMES_T" : 0, (esc)
  \t\t\t\t\t"PKMID_G" : 0, (esc)
  \t\t\t\t\t"PKMID_T" : 0, (esc)
  \t\t\t\t\t"PKZVAR_A" : 0, (esc)
  \t\t\t\t\t"PKZVAR_C" : 0, (esc)
  \t\t\t\t\t"PKZVAR_G" : 0, (esc)
  \t\t\t\t\t"PKZVAR_T" : 0, (esc)
  \t\t\t\t\t"PULSE_DETECTION_SCORE" : 0, (esc)
  \t\t\t\t\t"PULSE_WIDTH" : 0, (esc)
  \t\t\t\t\t"TRACE_AUTOCORR" : 0 (esc)
  \t\t\t\t}, (esc)
  \t\t\t\t{ (esc)
  \t\t\t\t\t"BASELINE_MEAN" : -1.158203125, (esc)
  \t\t\t\t\t"BASELINE_SD" : 15.171875, (esc)
  \t\t\t\t\t"BASE_WIDTH" : 26475, (esc)
  \t\t\t\t\t"BPZVAR_A" : 0, (esc)
  \t\t\t\t\t"BPZVAR_C" : 0, (esc)
  \t\t\t\t\t"BPZVAR_G" : 0, (esc)
  \t\t\t\t\t"BPZVAR_T" : 0, (esc)
  \t\t\t\t\t"DME_STATUS" : 0, (esc)
  \t\t\t\t\t"ID" : 1, (esc)
  \t\t\t\t\t"NUM_BASES_A" : 315, (esc)
  \t\t\t\t\t"NUM_BASES_C" : 321, (esc)
  \t\t\t\t\t"NUM_BASES_G" : 312, (esc)
  \t\t\t\t\t"NUM_BASES_T" : 365, (esc)
  \t\t\t\t\t"NUM_FRAMES" : 53760, (esc)
  \t\t\t\t\t"NUM_HALF_SANDWICHES" : 0, (esc)
  \t\t\t\t\t"NUM_PULSES" : 1320, (esc)
  \t\t\t\t\t"NUM_PULSE_LABEL_STUTTERS" : 0, (esc)
  \t\t\t\t\t"NUM_SANDWICHES" : 0, (esc)
  \t\t\t\t\t"PIXEL_CHECKSUM" : 0, (esc)
  \t\t\t\t\t"PKMAX_A" : 0, (esc)
  \t\t\t\t\t"PKMAX_C" : 0, (esc)
  \t\t\t\t\t"PKMAX_G" : 0, (esc)
  \t\t\t\t\t"PKMAX_T" : 0, (esc)
  \t\t\t\t\t"PKMID_A" : 227.625, (esc)
  \t\t\t\t\t"PKMID_C" : 157.125, (esc)
  \t\t\t\t\t"PKMID_FRAMES_A" : 6058, (esc)
  \t\t\t\t\t"PKMID_FRAMES_C" : 5051, (esc)
  \t\t\t\t\t"PKMID_FRAMES_G" : 4917, (esc)
  \t\t\t\t\t"PKMID_FRAMES_T" : 7823, (esc)
  \t\t\t\t\t"PKMID_G" : 98.8125, (esc)
  \t\t\t\t\t"PKMID_T" : 62.0625, (esc)
  \t\t\t\t\t"PKZVAR_A" : 0, (esc)
  \t\t\t\t\t"PKZVAR_C" : 0, (esc)
  \t\t\t\t\t"PKZVAR_G" : 0, (esc)
  \t\t\t\t\t"PKZVAR_T" : 0, (esc)
  \t\t\t\t\t"PULSE_DETECTION_SCORE" : 0, (esc)
  \t\t\t\t\t"PULSE_WIDTH" : 26489, (esc)
  \t\t\t\t\t"TRACE_AUTOCORR" : 0 (esc)
  \t\t\t\t} (esc)
  \t\t\t], (esc)
  \t\t\t"ZMW_ID" : 0, (esc)
  \t\t\t"ZMW_NUMBER" : 0 (esc)
  \t\t} (esc)
  \t], (esc)
  \t"TYPE" : "BAZ_OVERVIEW" (esc)
  }

# Run again but set the hqThrottleFraction=0.25 so start of HQ-region is different resulting in a preHQ metric block with data.
  $ smrt-basecaller --config source.TraceReplication='{"numFrames":57344, "numZmwLanes":4,"traceFile":"'$TRCFILE'" }' \
  > --config multipleBazFiles=false --config layout.lanesPerPool=1 --config=algorithm.modelEstimationMode=FixedEstimations  \
  > --outputbazfile ${BAZFILE} --config=prelimHQ.enablePreHQ=true --config=prelimHQ.hqThrottleFraction=0.25 > /dev/null

  $ bazviewer --silent -m -i0 ${BAZFILE} 
  {
  \t"METRICS" :  (esc)
  \t[ (esc)
  \t\t{ (esc)
  \t\t\t"INTERNAL" : false, (esc)
  \t\t\t"METRICS" :  (esc)
  \t\t\t[ (esc)
  \t\t\t\t{ (esc)
  \t\t\t\t\t"BASELINE_MEAN" : 0, (esc)
  \t\t\t\t\t"BASELINE_SD" : 0, (esc)
  \t\t\t\t\t"BASE_WIDTH" : 0, (esc)
  \t\t\t\t\t"BPZVAR_A" : 0, (esc)
  \t\t\t\t\t"BPZVAR_C" : 0, (esc)
  \t\t\t\t\t"BPZVAR_G" : 0, (esc)
  \t\t\t\t\t"BPZVAR_T" : 0, (esc)
  \t\t\t\t\t"DME_STATUS" : 0, (esc)
  \t\t\t\t\t"ID" : 0, (esc)
  \t\t\t\t\t"NUM_BASES_A" : 0, (esc)
  \t\t\t\t\t"NUM_BASES_C" : 0, (esc)
  \t\t\t\t\t"NUM_BASES_G" : 0, (esc)
  \t\t\t\t\t"NUM_BASES_T" : 0, (esc)
  \t\t\t\t\t"NUM_FRAMES" : 0, (esc)
  \t\t\t\t\t"NUM_HALF_SANDWICHES" : 0, (esc)
  \t\t\t\t\t"NUM_PULSES" : 0, (esc)
  \t\t\t\t\t"NUM_PULSE_LABEL_STUTTERS" : 0, (esc)
  \t\t\t\t\t"NUM_SANDWICHES" : 0, (esc)
  \t\t\t\t\t"PIXEL_CHECKSUM" : 0, (esc)
  \t\t\t\t\t"PKMAX_A" : 0, (esc)
  \t\t\t\t\t"PKMAX_C" : 0, (esc)
  \t\t\t\t\t"PKMAX_G" : 0, (esc)
  \t\t\t\t\t"PKMAX_T" : 0, (esc)
  \t\t\t\t\t"PKMID_A" : 0, (esc)
  \t\t\t\t\t"PKMID_C" : 0, (esc)
  \t\t\t\t\t"PKMID_FRAMES_A" : 0, (esc)
  \t\t\t\t\t"PKMID_FRAMES_C" : 0, (esc)
  \t\t\t\t\t"PKMID_FRAMES_G" : 0, (esc)
  \t\t\t\t\t"PKMID_FRAMES_T" : 0, (esc)
  \t\t\t\t\t"PKMID_G" : 0, (esc)
  \t\t\t\t\t"PKMID_T" : 0, (esc)
  \t\t\t\t\t"PKZVAR_A" : 0, (esc)
  \t\t\t\t\t"PKZVAR_C" : 0, (esc)
  \t\t\t\t\t"PKZVAR_G" : 0, (esc)
  \t\t\t\t\t"PKZVAR_T" : 0, (esc)
  \t\t\t\t\t"PULSE_DETECTION_SCORE" : 0, (esc)
  \t\t\t\t\t"PULSE_WIDTH" : 0, (esc)
  \t\t\t\t\t"TRACE_AUTOCORR" : 0 (esc)
  \t\t\t\t}, (esc)
  \t\t\t\t{ (esc)
  \t\t\t\t\t"BASELINE_MEAN" : -1.158203125, (esc)
  \t\t\t\t\t"BASELINE_SD" : 15.171875, (esc)
  \t\t\t\t\t"BASE_WIDTH" : 26475, (esc)
  \t\t\t\t\t"BPZVAR_A" : 0, (esc)
  \t\t\t\t\t"BPZVAR_C" : 0, (esc)
  \t\t\t\t\t"BPZVAR_G" : 0, (esc)
  \t\t\t\t\t"BPZVAR_T" : 0, (esc)
  \t\t\t\t\t"DME_STATUS" : 0, (esc)
  \t\t\t\t\t"ID" : 1, (esc)
  \t\t\t\t\t"NUM_BASES_A" : 315, (esc)
  \t\t\t\t\t"NUM_BASES_C" : 321, (esc)
  \t\t\t\t\t"NUM_BASES_G" : 312, (esc)
  \t\t\t\t\t"NUM_BASES_T" : 365, (esc)
  \t\t\t\t\t"NUM_FRAMES" : 53760, (esc)
  \t\t\t\t\t"NUM_HALF_SANDWICHES" : 0, (esc)
  \t\t\t\t\t"NUM_PULSES" : 1320, (esc)
  \t\t\t\t\t"NUM_PULSE_LABEL_STUTTERS" : 0, (esc)
  \t\t\t\t\t"NUM_SANDWICHES" : 0, (esc)
  \t\t\t\t\t"PIXEL_CHECKSUM" : 0, (esc)
  \t\t\t\t\t"PKMAX_A" : 0, (esc)
  \t\t\t\t\t"PKMAX_C" : 0, (esc)
  \t\t\t\t\t"PKMAX_G" : 0, (esc)
  \t\t\t\t\t"PKMAX_T" : 0, (esc)
  \t\t\t\t\t"PKMID_A" : 227.625, (esc)
  \t\t\t\t\t"PKMID_C" : 157.125, (esc)
  \t\t\t\t\t"PKMID_FRAMES_A" : 6058, (esc)
  \t\t\t\t\t"PKMID_FRAMES_C" : 5051, (esc)
  \t\t\t\t\t"PKMID_FRAMES_G" : 4917, (esc)
  \t\t\t\t\t"PKMID_FRAMES_T" : 7823, (esc)
  \t\t\t\t\t"PKMID_G" : 98.8125, (esc)
  \t\t\t\t\t"PKMID_T" : 62.0625, (esc)
  \t\t\t\t\t"PKZVAR_A" : 0, (esc)
  \t\t\t\t\t"PKZVAR_C" : 0, (esc)
  \t\t\t\t\t"PKZVAR_G" : 0, (esc)
  \t\t\t\t\t"PKZVAR_T" : 0, (esc)
  \t\t\t\t\t"PULSE_DETECTION_SCORE" : 0, (esc)
  \t\t\t\t\t"PULSE_WIDTH" : 26489, (esc)
  \t\t\t\t\t"TRACE_AUTOCORR" : 0 (esc)
  \t\t\t\t} (esc)
  \t\t\t], (esc)
  \t\t\t"ZMW_ID" : 0, (esc)
  \t\t\t"ZMW_NUMBER" : 0 (esc)
  \t\t} (esc)
  \t], (esc)
  \t"TYPE" : "BAZ_OVERVIEW" (esc)
  }

  $ bazviewer --silent -m -i1 ${BAZFILE} 
  {
  \t"METRICS" :  (esc)
  \t[ (esc)
  \t\t{ (esc)
  \t\t\t"INTERNAL" : false, (esc)
  \t\t\t"METRICS" :  (esc)
  \t\t\t[ (esc)
  \t\t\t\t{ (esc)
  \t\t\t\t\t"BASELINE_MEAN" : 0.08758544921875, (esc)
  \t\t\t\t\t"BASELINE_SD" : 5.23828125, (esc)
  \t\t\t\t\t"BASE_WIDTH" : 280, (esc)
  \t\t\t\t\t"BPZVAR_A" : 0, (esc)
  \t\t\t\t\t"BPZVAR_C" : 0, (esc)
  \t\t\t\t\t"BPZVAR_G" : 0, (esc)
  \t\t\t\t\t"BPZVAR_T" : 0, (esc)
  \t\t\t\t\t"DME_STATUS" : 0, (esc)
  \t\t\t\t\t"ID" : 0, (esc)
  \t\t\t\t\t"NUM_BASES_A" : 2, (esc)
  \t\t\t\t\t"NUM_BASES_C" : 1, (esc)
  \t\t\t\t\t"NUM_BASES_G" : 7, (esc)
  \t\t\t\t\t"NUM_BASES_T" : 3, (esc)
  \t\t\t\t\t"NUM_FRAMES" : 512, (esc)
  \t\t\t\t\t"NUM_HALF_SANDWICHES" : 0, (esc)
  \t\t\t\t\t"NUM_PULSES" : 13, (esc)
  \t\t\t\t\t"NUM_PULSE_LABEL_STUTTERS" : 0, (esc)
  \t\t\t\t\t"NUM_SANDWICHES" : 0, (esc)
  \t\t\t\t\t"PIXEL_CHECKSUM" : 0, (esc)
  \t\t\t\t\t"PKMAX_A" : 0, (esc)
  \t\t\t\t\t"PKMAX_C" : 0, (esc)
  \t\t\t\t\t"PKMAX_G" : 0, (esc)
  \t\t\t\t\t"PKMAX_T" : 0, (esc)
  \t\t\t\t\t"PKMID_A" : 226.375, (esc)
  \t\t\t\t\t"PKMID_C" : 0, (esc)
  \t\t\t\t\t"PKMID_FRAMES_A" : 11, (esc)
  \t\t\t\t\t"PKMID_FRAMES_C" : 0, (esc)
  \t\t\t\t\t"PKMID_FRAMES_G" : 173, (esc)
  \t\t\t\t\t"PKMID_FRAMES_T" : 70, (esc)
  \t\t\t\t\t"PKMID_G" : 100.25, (esc)
  \t\t\t\t\t"PKMID_T" : 63.8125, (esc)
  \t\t\t\t\t"PKZVAR_A" : 0, (esc)
  \t\t\t\t\t"PKZVAR_C" : 0, (esc)
  \t\t\t\t\t"PKZVAR_G" : 0, (esc)
  \t\t\t\t\t"PKZVAR_T" : 0, (esc)
  \t\t\t\t\t"PULSE_DETECTION_SCORE" : 0, (esc)
  \t\t\t\t\t"PULSE_WIDTH" : 280, (esc)
  \t\t\t\t\t"TRACE_AUTOCORR" : 0 (esc)
  \t\t\t\t}, (esc)
  \t\t\t\t{ (esc)
  \t\t\t\t\t"BASELINE_MEAN" : 0.032012939453125, (esc)
  \t\t\t\t\t"BASELINE_SD" : 5.96484375, (esc)
  \t\t\t\t\t"BASE_WIDTH" : 1908, (esc)
  \t\t\t\t\t"BPZVAR_A" : 0, (esc)
  \t\t\t\t\t"BPZVAR_C" : 0, (esc)
  \t\t\t\t\t"BPZVAR_G" : 0, (esc)
  \t\t\t\t\t"BPZVAR_T" : 0, (esc)
  \t\t\t\t\t"DME_STATUS" : 0, (esc)
  \t\t\t\t\t"ID" : 1, (esc)
  \t\t\t\t\t"NUM_BASES_A" : 27, (esc)
  \t\t\t\t\t"NUM_BASES_C" : 28, (esc)
  \t\t\t\t\t"NUM_BASES_G" : 22, (esc)
  \t\t\t\t\t"NUM_BASES_T" : 19, (esc)
  \t\t\t\t\t"NUM_FRAMES" : 4096, (esc)
  \t\t\t\t\t"NUM_HALF_SANDWICHES" : 0, (esc)
  \t\t\t\t\t"NUM_PULSES" : 98, (esc)
  \t\t\t\t\t"NUM_PULSE_LABEL_STUTTERS" : 0, (esc)
  \t\t\t\t\t"NUM_SANDWICHES" : 0, (esc)
  \t\t\t\t\t"PIXEL_CHECKSUM" : 0, (esc)
  \t\t\t\t\t"PKMAX_A" : 0, (esc)
  \t\t\t\t\t"PKMAX_C" : 0, (esc)
  \t\t\t\t\t"PKMAX_G" : 0, (esc)
  \t\t\t\t\t"PKMAX_T" : 0, (esc)
  \t\t\t\t\t"PKMID_A" : 229.375, (esc)
  \t\t\t\t\t"PKMID_C" : 155.875, (esc)
  \t\t\t\t\t"PKMID_FRAMES_A" : 554, (esc)
  \t\t\t\t\t"PKMID_FRAMES_C" : 543, (esc)
  \t\t\t\t\t"PKMID_FRAMES_G" : 321, (esc)
  \t\t\t\t\t"PKMID_FRAMES_T" : 298, (esc)
  \t\t\t\t\t"PKMID_G" : 99.875, (esc)
  \t\t\t\t\t"PKMID_T" : 62.78125, (esc)
  \t\t\t\t\t"PKZVAR_A" : 0, (esc)
  \t\t\t\t\t"PKZVAR_C" : 0, (esc)
  \t\t\t\t\t"PKZVAR_G" : 0, (esc)
  \t\t\t\t\t"PKZVAR_T" : 0, (esc)
  \t\t\t\t\t"PULSE_DETECTION_SCORE" : 0, (esc)
  \t\t\t\t\t"PULSE_WIDTH" : 1912, (esc)
  \t\t\t\t\t"TRACE_AUTOCORR" : 0 (esc)
  \t\t\t\t}, (esc)
  \t\t\t\t{ (esc)
  \t\t\t\t\t"BASELINE_MEAN" : -0.03515625, (esc)
  \t\t\t\t\t"BASELINE_SD" : 7.875, (esc)
  \t\t\t\t\t"BASE_WIDTH" : 1925, (esc)
  \t\t\t\t\t"BPZVAR_A" : 0, (esc)
  \t\t\t\t\t"BPZVAR_C" : 0, (esc)
  \t\t\t\t\t"BPZVAR_G" : 0, (esc)
  \t\t\t\t\t"BPZVAR_T" : 0, (esc)
  \t\t\t\t\t"DME_STATUS" : 0, (esc)
  \t\t\t\t\t"ID" : 2, (esc)
  \t\t\t\t\t"NUM_BASES_A" : 30, (esc)
  \t\t\t\t\t"NUM_BASES_C" : 32, (esc)
  \t\t\t\t\t"NUM_BASES_G" : 24, (esc)
  \t\t\t\t\t"NUM_BASES_T" : 15, (esc)
  \t\t\t\t\t"NUM_FRAMES" : 4096, (esc)
  \t\t\t\t\t"NUM_HALF_SANDWICHES" : 0, (esc)
  \t\t\t\t\t"NUM_PULSES" : 101, (esc)
  \t\t\t\t\t"NUM_PULSE_LABEL_STUTTERS" : 0, (esc)
  \t\t\t\t\t"NUM_SANDWICHES" : 0, (esc)
  \t\t\t\t\t"PIXEL_CHECKSUM" : 0, (esc)
  \t\t\t\t\t"PKMAX_A" : 0, (esc)
  \t\t\t\t\t"PKMAX_C" : 0, (esc)
  \t\t\t\t\t"PKMAX_G" : 0, (esc)
  \t\t\t\t\t"PKMAX_T" : 0, (esc)
  \t\t\t\t\t"PKMID_A" : 230, (esc)
  \t\t\t\t\t"PKMID_C" : 157.625, (esc)
  \t\t\t\t\t"PKMID_FRAMES_A" : 525, (esc)
  \t\t\t\t\t"PKMID_FRAMES_C" : 426, (esc)
  \t\t\t\t\t"PKMID_FRAMES_G" : 387, (esc)
  \t\t\t\t\t"PKMID_FRAMES_T" : 386, (esc)
  \t\t\t\t\t"PKMID_G" : 100.9375, (esc)
  \t\t\t\t\t"PKMID_T" : 62.25, (esc)
  \t\t\t\t\t"PKZVAR_A" : 0, (esc)
  \t\t\t\t\t"PKZVAR_C" : 0, (esc)
  \t\t\t\t\t"PKZVAR_G" : 0, (esc)
  \t\t\t\t\t"PKZVAR_T" : 0, (esc)
  \t\t\t\t\t"PULSE_DETECTION_SCORE" : 0, (esc)
  \t\t\t\t\t"PULSE_WIDTH" : 1925, (esc)
  \t\t\t\t\t"TRACE_AUTOCORR" : 0 (esc)
  \t\t\t\t}, (esc)
  \t\t\t\t{ (esc)
  \t\t\t\t\t"BASELINE_MEAN" : 0.157958984375, (esc)
  \t\t\t\t\t"BASELINE_SD" : 9.890625, (esc)
  \t\t\t\t\t"BASE_WIDTH" : 1908, (esc)
  \t\t\t\t\t"BPZVAR_A" : 0, (esc)
  \t\t\t\t\t"BPZVAR_C" : 0, (esc)
  \t\t\t\t\t"BPZVAR_G" : 0, (esc)
  \t\t\t\t\t"BPZVAR_T" : 0, (esc)
  \t\t\t\t\t"DME_STATUS" : 0, (esc)
  \t\t\t\t\t"ID" : 3, (esc)
  \t\t\t\t\t"NUM_BASES_A" : 27, (esc)
  \t\t\t\t\t"NUM_BASES_C" : 28, (esc)
  \t\t\t\t\t"NUM_BASES_G" : 22, (esc)
  \t\t\t\t\t"NUM_BASES_T" : 19, (esc)
  \t\t\t\t\t"NUM_FRAMES" : 4096, (esc)
  \t\t\t\t\t"NUM_HALF_SANDWICHES" : 0, (esc)
  \t\t\t\t\t"NUM_PULSES" : 98, (esc)
  \t\t\t\t\t"NUM_PULSE_LABEL_STUTTERS" : 0, (esc)
  \t\t\t\t\t"NUM_SANDWICHES" : 0, (esc)
  \t\t\t\t\t"PIXEL_CHECKSUM" : 0, (esc)
  \t\t\t\t\t"PKMAX_A" : 0, (esc)
  \t\t\t\t\t"PKMAX_C" : 0, (esc)
  \t\t\t\t\t"PKMAX_G" : 0, (esc)
  \t\t\t\t\t"PKMAX_T" : 0, (esc)
  \t\t\t\t\t"PKMID_A" : 229.375, (esc)
  \t\t\t\t\t"PKMID_C" : 155.875, (esc)
  \t\t\t\t\t"PKMID_FRAMES_A" : 554, (esc)
  \t\t\t\t\t"PKMID_FRAMES_C" : 543, (esc)
  \t\t\t\t\t"PKMID_FRAMES_G" : 321, (esc)
  \t\t\t\t\t"PKMID_FRAMES_T" : 298, (esc)
  \t\t\t\t\t"PKMID_G" : 99.875, (esc)
  \t\t\t\t\t"PKMID_T" : 62.78125, (esc)
  \t\t\t\t\t"PKZVAR_A" : 0, (esc)
  \t\t\t\t\t"PKZVAR_C" : 0, (esc)
  \t\t\t\t\t"PKZVAR_G" : 0, (esc)
  \t\t\t\t\t"PKZVAR_T" : 0, (esc)
  \t\t\t\t\t"PULSE_DETECTION_SCORE" : 0, (esc)
  \t\t\t\t\t"PULSE_WIDTH" : 1912, (esc)
  \t\t\t\t\t"TRACE_AUTOCORR" : 0 (esc)
  \t\t\t\t}, (esc)
  \t\t\t\t{ (esc)
  \t\t\t\t\t"BASELINE_MEAN" : 0.10205078125, (esc)
  \t\t\t\t\t"BASELINE_SD" : 11.703125, (esc)
  \t\t\t\t\t"BASE_WIDTH" : 1925, (esc)
  \t\t\t\t\t"BPZVAR_A" : 0, (esc)
  \t\t\t\t\t"BPZVAR_C" : 0, (esc)
  \t\t\t\t\t"BPZVAR_G" : 0, (esc)
  \t\t\t\t\t"BPZVAR_T" : 0, (esc)
  \t\t\t\t\t"DME_STATUS" : 0, (esc)
  \t\t\t\t\t"ID" : 4, (esc)
  \t\t\t\t\t"NUM_BASES_A" : 30, (esc)
  \t\t\t\t\t"NUM_BASES_C" : 32, (esc)
  \t\t\t\t\t"NUM_BASES_G" : 24, (esc)
  \t\t\t\t\t"NUM_BASES_T" : 15, (esc)
  \t\t\t\t\t"NUM_FRAMES" : 4096, (esc)
  \t\t\t\t\t"NUM_HALF_SANDWICHES" : 0, (esc)
  \t\t\t\t\t"NUM_PULSES" : 101, (esc)
  \t\t\t\t\t"NUM_PULSE_LABEL_STUTTERS" : 0, (esc)
  \t\t\t\t\t"NUM_SANDWICHES" : 0, (esc)
  \t\t\t\t\t"PIXEL_CHECKSUM" : 0, (esc)
  \t\t\t\t\t"PKMAX_A" : 0, (esc)
  \t\t\t\t\t"PKMAX_C" : 0, (esc)
  \t\t\t\t\t"PKMAX_G" : 0, (esc)
  \t\t\t\t\t"PKMAX_T" : 0, (esc)
  \t\t\t\t\t"PKMID_A" : 230, (esc)
  \t\t\t\t\t"PKMID_C" : 157.625, (esc)
  \t\t\t\t\t"PKMID_FRAMES_A" : 525, (esc)
  \t\t\t\t\t"PKMID_FRAMES_C" : 426, (esc)
  \t\t\t\t\t"PKMID_FRAMES_G" : 387, (esc)
  \t\t\t\t\t"PKMID_FRAMES_T" : 386, (esc)
  \t\t\t\t\t"PKMID_G" : 100.9375, (esc)
  \t\t\t\t\t"PKMID_T" : 62.25, (esc)
  \t\t\t\t\t"PKZVAR_A" : 0, (esc)
  \t\t\t\t\t"PKZVAR_C" : 0, (esc)
  \t\t\t\t\t"PKZVAR_G" : 0, (esc)
  \t\t\t\t\t"PKZVAR_T" : 0, (esc)
  \t\t\t\t\t"PULSE_DETECTION_SCORE" : 0, (esc)
  \t\t\t\t\t"PULSE_WIDTH" : 1925, (esc)
  \t\t\t\t\t"TRACE_AUTOCORR" : 0 (esc)
  \t\t\t\t}, (esc)
  \t\t\t\t{ (esc)
  \t\t\t\t\t"BASELINE_MEAN" : 0.295166015625, (esc)
  \t\t\t\t\t"BASELINE_SD" : 13.140625, (esc)
  \t\t\t\t\t"BASE_WIDTH" : 1908, (esc)
  \t\t\t\t\t"BPZVAR_A" : 0, (esc)
  \t\t\t\t\t"BPZVAR_C" : 0, (esc)
  \t\t\t\t\t"BPZVAR_G" : 0, (esc)
  \t\t\t\t\t"BPZVAR_T" : 0, (esc)
  \t\t\t\t\t"DME_STATUS" : 0, (esc)
  \t\t\t\t\t"ID" : 5, (esc)
  \t\t\t\t\t"NUM_BASES_A" : 27, (esc)
  \t\t\t\t\t"NUM_BASES_C" : 28, (esc)
  \t\t\t\t\t"NUM_BASES_G" : 22, (esc)
  \t\t\t\t\t"NUM_BASES_T" : 19, (esc)
  \t\t\t\t\t"NUM_FRAMES" : 4096, (esc)
  \t\t\t\t\t"NUM_HALF_SANDWICHES" : 0, (esc)
  \t\t\t\t\t"NUM_PULSES" : 98, (esc)
  \t\t\t\t\t"NUM_PULSE_LABEL_STUTTERS" : 0, (esc)
  \t\t\t\t\t"NUM_SANDWICHES" : 0, (esc)
  \t\t\t\t\t"PIXEL_CHECKSUM" : 0, (esc)
  \t\t\t\t\t"PKMAX_A" : 0, (esc)
  \t\t\t\t\t"PKMAX_C" : 0, (esc)
  \t\t\t\t\t"PKMAX_G" : 0, (esc)
  \t\t\t\t\t"PKMAX_T" : 0, (esc)
  \t\t\t\t\t"PKMID_A" : 229.375, (esc)
  \t\t\t\t\t"PKMID_C" : 155.875, (esc)
  \t\t\t\t\t"PKMID_FRAMES_A" : 554, (esc)
  \t\t\t\t\t"PKMID_FRAMES_C" : 543, (esc)
  \t\t\t\t\t"PKMID_FRAMES_G" : 321, (esc)
  \t\t\t\t\t"PKMID_FRAMES_T" : 298, (esc)
  \t\t\t\t\t"PKMID_G" : 99.875, (esc)
  \t\t\t\t\t"PKMID_T" : 62.78125, (esc)
  \t\t\t\t\t"PKZVAR_A" : 0, (esc)
  \t\t\t\t\t"PKZVAR_C" : 0, (esc)
  \t\t\t\t\t"PKZVAR_G" : 0, (esc)
  \t\t\t\t\t"PKZVAR_T" : 0, (esc)
  \t\t\t\t\t"PULSE_DETECTION_SCORE" : 0, (esc)
  \t\t\t\t\t"PULSE_WIDTH" : 1912, (esc)
  \t\t\t\t\t"TRACE_AUTOCORR" : 0 (esc)
  \t\t\t\t}, (esc)
  \t\t\t\t{ (esc)
  \t\t\t\t\t"BASELINE_MEAN" : 0.2392578125, (esc)
  \t\t\t\t\t"BASELINE_SD" : 14.546875, (esc)
  \t\t\t\t\t"BASE_WIDTH" : 1925, (esc)
  \t\t\t\t\t"BPZVAR_A" : 0, (esc)
  \t\t\t\t\t"BPZVAR_C" : 0, (esc)
  \t\t\t\t\t"BPZVAR_G" : 0, (esc)
  \t\t\t\t\t"BPZVAR_T" : 0, (esc)
  \t\t\t\t\t"DME_STATUS" : 0, (esc)
  \t\t\t\t\t"ID" : 6, (esc)
  \t\t\t\t\t"NUM_BASES_A" : 30, (esc)
  \t\t\t\t\t"NUM_BASES_C" : 32, (esc)
  \t\t\t\t\t"NUM_BASES_G" : 24, (esc)
  \t\t\t\t\t"NUM_BASES_T" : 15, (esc)
  \t\t\t\t\t"NUM_FRAMES" : 4096, (esc)
  \t\t\t\t\t"NUM_HALF_SANDWICHES" : 0, (esc)
  \t\t\t\t\t"NUM_PULSES" : 101, (esc)
  \t\t\t\t\t"NUM_PULSE_LABEL_STUTTERS" : 0, (esc)
  \t\t\t\t\t"NUM_SANDWICHES" : 0, (esc)
  \t\t\t\t\t"PIXEL_CHECKSUM" : 0, (esc)
  \t\t\t\t\t"PKMAX_A" : 0, (esc)
  \t\t\t\t\t"PKMAX_C" : 0, (esc)
  \t\t\t\t\t"PKMAX_G" : 0, (esc)
  \t\t\t\t\t"PKMAX_T" : 0, (esc)
  \t\t\t\t\t"PKMID_A" : 230, (esc)
  \t\t\t\t\t"PKMID_C" : 157.625, (esc)
  \t\t\t\t\t"PKMID_FRAMES_A" : 525, (esc)
  \t\t\t\t\t"PKMID_FRAMES_C" : 426, (esc)
  \t\t\t\t\t"PKMID_FRAMES_G" : 387, (esc)
  \t\t\t\t\t"PKMID_FRAMES_T" : 386, (esc)
  \t\t\t\t\t"PKMID_G" : 100.9375, (esc)
  \t\t\t\t\t"PKMID_T" : 62.25, (esc)
  \t\t\t\t\t"PKZVAR_A" : 0, (esc)
  \t\t\t\t\t"PKZVAR_C" : 0, (esc)
  \t\t\t\t\t"PKZVAR_G" : 0, (esc)
  \t\t\t\t\t"PKZVAR_T" : 0, (esc)
  \t\t\t\t\t"PULSE_DETECTION_SCORE" : 0, (esc)
  \t\t\t\t\t"PULSE_WIDTH" : 1925, (esc)
  \t\t\t\t\t"TRACE_AUTOCORR" : 0 (esc)
  \t\t\t\t}, (esc)
  \t\t\t\t{ (esc)
  \t\t\t\t\t"BASELINE_MEAN" : 0.432373046875, (esc)
  \t\t\t\t\t"BASELINE_SD" : 15.7265625, (esc)
  \t\t\t\t\t"BASE_WIDTH" : 1908, (esc)
  \t\t\t\t\t"BPZVAR_A" : 0, (esc)
  \t\t\t\t\t"BPZVAR_C" : 0, (esc)
  \t\t\t\t\t"BPZVAR_G" : 0, (esc)
  \t\t\t\t\t"BPZVAR_T" : 0, (esc)
  \t\t\t\t\t"DME_STATUS" : 0, (esc)
  \t\t\t\t\t"ID" : 7, (esc)
  \t\t\t\t\t"NUM_BASES_A" : 27, (esc)
  \t\t\t\t\t"NUM_BASES_C" : 28, (esc)
  \t\t\t\t\t"NUM_BASES_G" : 22, (esc)
  \t\t\t\t\t"NUM_BASES_T" : 19, (esc)
  \t\t\t\t\t"NUM_FRAMES" : 4096, (esc)
  \t\t\t\t\t"NUM_HALF_SANDWICHES" : 0, (esc)
  \t\t\t\t\t"NUM_PULSES" : 98, (esc)
  \t\t\t\t\t"NUM_PULSE_LABEL_STUTTERS" : 0, (esc)
  \t\t\t\t\t"NUM_SANDWICHES" : 0, (esc)
  \t\t\t\t\t"PIXEL_CHECKSUM" : 0, (esc)
  \t\t\t\t\t"PKMAX_A" : 0, (esc)
  \t\t\t\t\t"PKMAX_C" : 0, (esc)
  \t\t\t\t\t"PKMAX_G" : 0, (esc)
  \t\t\t\t\t"PKMAX_T" : 0, (esc)
  \t\t\t\t\t"PKMID_A" : 229.375, (esc)
  \t\t\t\t\t"PKMID_C" : 155.875, (esc)
  \t\t\t\t\t"PKMID_FRAMES_A" : 554, (esc)
  \t\t\t\t\t"PKMID_FRAMES_C" : 543, (esc)
  \t\t\t\t\t"PKMID_FRAMES_G" : 321, (esc)
  \t\t\t\t\t"PKMID_FRAMES_T" : 298, (esc)
  \t\t\t\t\t"PKMID_G" : 99.875, (esc)
  \t\t\t\t\t"PKMID_T" : 62.78125, (esc)
  \t\t\t\t\t"PKZVAR_A" : 0, (esc)
  \t\t\t\t\t"PKZVAR_C" : 0, (esc)
  \t\t\t\t\t"PKZVAR_G" : 0, (esc)
  \t\t\t\t\t"PKZVAR_T" : 0, (esc)
  \t\t\t\t\t"PULSE_DETECTION_SCORE" : 0, (esc)
  \t\t\t\t\t"PULSE_WIDTH" : 1912, (esc)
  \t\t\t\t\t"TRACE_AUTOCORR" : 0 (esc)
  \t\t\t\t}, (esc)
  \t\t\t\t{ (esc)
  \t\t\t\t\t"BASELINE_MEAN" : 0.37646484375, (esc)
  \t\t\t\t\t"BASELINE_SD" : 16.921875, (esc)
  \t\t\t\t\t"BASE_WIDTH" : 1925, (esc)
  \t\t\t\t\t"BPZVAR_A" : 0, (esc)
  \t\t\t\t\t"BPZVAR_C" : 0, (esc)
  \t\t\t\t\t"BPZVAR_G" : 0, (esc)
  \t\t\t\t\t"BPZVAR_T" : 0, (esc)
  \t\t\t\t\t"DME_STATUS" : 0, (esc)
  \t\t\t\t\t"ID" : 8, (esc)
  \t\t\t\t\t"NUM_BASES_A" : 30, (esc)
  \t\t\t\t\t"NUM_BASES_C" : 32, (esc)
  \t\t\t\t\t"NUM_BASES_G" : 24, (esc)
  \t\t\t\t\t"NUM_BASES_T" : 15, (esc)
  \t\t\t\t\t"NUM_FRAMES" : 4096, (esc)
  \t\t\t\t\t"NUM_HALF_SANDWICHES" : 0, (esc)
  \t\t\t\t\t"NUM_PULSES" : 101, (esc)
  \t\t\t\t\t"NUM_PULSE_LABEL_STUTTERS" : 0, (esc)
  \t\t\t\t\t"NUM_SANDWICHES" : 0, (esc)
  \t\t\t\t\t"PIXEL_CHECKSUM" : 0, (esc)
  \t\t\t\t\t"PKMAX_A" : 0, (esc)
  \t\t\t\t\t"PKMAX_C" : 0, (esc)
  \t\t\t\t\t"PKMAX_G" : 0, (esc)
  \t\t\t\t\t"PKMAX_T" : 0, (esc)
  \t\t\t\t\t"PKMID_A" : 230, (esc)
  \t\t\t\t\t"PKMID_C" : 157.625, (esc)
  \t\t\t\t\t"PKMID_FRAMES_A" : 525, (esc)
  \t\t\t\t\t"PKMID_FRAMES_C" : 426, (esc)
  \t\t\t\t\t"PKMID_FRAMES_G" : 387, (esc)
  \t\t\t\t\t"PKMID_FRAMES_T" : 386, (esc)
  \t\t\t\t\t"PKMID_G" : 100.9375, (esc)
  \t\t\t\t\t"PKMID_T" : 62.25, (esc)
  \t\t\t\t\t"PKZVAR_A" : 0, (esc)
  \t\t\t\t\t"PKZVAR_C" : 0, (esc)
  \t\t\t\t\t"PKZVAR_G" : 0, (esc)
  \t\t\t\t\t"PKZVAR_T" : 0, (esc)
  \t\t\t\t\t"PULSE_DETECTION_SCORE" : 0, (esc)
  \t\t\t\t\t"PULSE_WIDTH" : 1925, (esc)
  \t\t\t\t\t"TRACE_AUTOCORR" : 0 (esc)
  \t\t\t\t}, (esc)
  \t\t\t\t{ (esc)
  \t\t\t\t\t"BASELINE_MEAN" : 0.5712890625, (esc)
  \t\t\t\t\t"BASELINE_SD" : 17.9375, (esc)
  \t\t\t\t\t"BASE_WIDTH" : 1908, (esc)
  \t\t\t\t\t"BPZVAR_A" : 0, (esc)
  \t\t\t\t\t"BPZVAR_C" : 0, (esc)
  \t\t\t\t\t"BPZVAR_G" : 0, (esc)
  \t\t\t\t\t"BPZVAR_T" : 0, (esc)
  \t\t\t\t\t"DME_STATUS" : 0, (esc)
  \t\t\t\t\t"ID" : 9, (esc)
  \t\t\t\t\t"NUM_BASES_A" : 27, (esc)
  \t\t\t\t\t"NUM_BASES_C" : 28, (esc)
  \t\t\t\t\t"NUM_BASES_G" : 22, (esc)
  \t\t\t\t\t"NUM_BASES_T" : 19, (esc)
  \t\t\t\t\t"NUM_FRAMES" : 4096, (esc)
  \t\t\t\t\t"NUM_HALF_SANDWICHES" : 0, (esc)
  \t\t\t\t\t"NUM_PULSES" : 98, (esc)
  \t\t\t\t\t"NUM_PULSE_LABEL_STUTTERS" : 0, (esc)
  \t\t\t\t\t"NUM_SANDWICHES" : 0, (esc)
  \t\t\t\t\t"PIXEL_CHECKSUM" : 0, (esc)
  \t\t\t\t\t"PKMAX_A" : 0, (esc)
  \t\t\t\t\t"PKMAX_C" : 0, (esc)
  \t\t\t\t\t"PKMAX_G" : 0, (esc)
  \t\t\t\t\t"PKMAX_T" : 0, (esc)
  \t\t\t\t\t"PKMID_A" : 229.375, (esc)
  \t\t\t\t\t"PKMID_C" : 155.875, (esc)
  \t\t\t\t\t"PKMID_FRAMES_A" : 554, (esc)
  \t\t\t\t\t"PKMID_FRAMES_C" : 543, (esc)
  \t\t\t\t\t"PKMID_FRAMES_G" : 321, (esc)
  \t\t\t\t\t"PKMID_FRAMES_T" : 298, (esc)
  \t\t\t\t\t"PKMID_G" : 99.875, (esc)
  \t\t\t\t\t"PKMID_T" : 62.78125, (esc)
  \t\t\t\t\t"PKZVAR_A" : 0, (esc)
  \t\t\t\t\t"PKZVAR_C" : 0, (esc)
  \t\t\t\t\t"PKZVAR_G" : 0, (esc)
  \t\t\t\t\t"PKZVAR_T" : 0, (esc)
  \t\t\t\t\t"PULSE_DETECTION_SCORE" : 0, (esc)
  \t\t\t\t\t"PULSE_WIDTH" : 1912, (esc)
  \t\t\t\t\t"TRACE_AUTOCORR" : 0 (esc)
  \t\t\t\t}, (esc)
  \t\t\t\t{ (esc)
  \t\t\t\t\t"BASELINE_MEAN" : 0.515625, (esc)
  \t\t\t\t\t"BASELINE_SD" : 19, (esc)
  \t\t\t\t\t"BASE_WIDTH" : 1925, (esc)
  \t\t\t\t\t"BPZVAR_A" : 0, (esc)
  \t\t\t\t\t"BPZVAR_C" : 0, (esc)
  \t\t\t\t\t"BPZVAR_G" : 0, (esc)
  \t\t\t\t\t"BPZVAR_T" : 0, (esc)
  \t\t\t\t\t"DME_STATUS" : 0, (esc)
  \t\t\t\t\t"ID" : 10, (esc)
  \t\t\t\t\t"NUM_BASES_A" : 30, (esc)
  \t\t\t\t\t"NUM_BASES_C" : 32, (esc)
  \t\t\t\t\t"NUM_BASES_G" : 24, (esc)
  \t\t\t\t\t"NUM_BASES_T" : 15, (esc)
  \t\t\t\t\t"NUM_FRAMES" : 4096, (esc)
  \t\t\t\t\t"NUM_HALF_SANDWICHES" : 0, (esc)
  \t\t\t\t\t"NUM_PULSES" : 101, (esc)
  \t\t\t\t\t"NUM_PULSE_LABEL_STUTTERS" : 0, (esc)
  \t\t\t\t\t"NUM_SANDWICHES" : 0, (esc)
  \t\t\t\t\t"PIXEL_CHECKSUM" : 0, (esc)
  \t\t\t\t\t"PKMAX_A" : 0, (esc)
  \t\t\t\t\t"PKMAX_C" : 0, (esc)
  \t\t\t\t\t"PKMAX_G" : 0, (esc)
  \t\t\t\t\t"PKMAX_T" : 0, (esc)
  \t\t\t\t\t"PKMID_A" : 230, (esc)
  \t\t\t\t\t"PKMID_C" : 157.625, (esc)
  \t\t\t\t\t"PKMID_FRAMES_A" : 525, (esc)
  \t\t\t\t\t"PKMID_FRAMES_C" : 426, (esc)
  \t\t\t\t\t"PKMID_FRAMES_G" : 387, (esc)
  \t\t\t\t\t"PKMID_FRAMES_T" : 386, (esc)
  \t\t\t\t\t"PKMID_G" : 100.9375, (esc)
  \t\t\t\t\t"PKMID_T" : 62.25, (esc)
  \t\t\t\t\t"PKZVAR_A" : 0, (esc)
  \t\t\t\t\t"PKZVAR_C" : 0, (esc)
  \t\t\t\t\t"PKZVAR_G" : 0, (esc)
  \t\t\t\t\t"PKZVAR_T" : 0, (esc)
  \t\t\t\t\t"PULSE_DETECTION_SCORE" : 0, (esc)
  \t\t\t\t\t"PULSE_WIDTH" : 1925, (esc)
  \t\t\t\t\t"TRACE_AUTOCORR" : 0 (esc)
  \t\t\t\t}, (esc)
  \t\t\t\t{ (esc)
  \t\t\t\t\t"BASELINE_MEAN" : 0.7099609375, (esc)
  \t\t\t\t\t"BASELINE_SD" : 19.921875, (esc)
  \t\t\t\t\t"BASE_WIDTH" : 1908, (esc)
  \t\t\t\t\t"BPZVAR_A" : 0, (esc)
  \t\t\t\t\t"BPZVAR_C" : 0, (esc)
  \t\t\t\t\t"BPZVAR_G" : 0, (esc)
  \t\t\t\t\t"BPZVAR_T" : 0, (esc)
  \t\t\t\t\t"DME_STATUS" : 0, (esc)
  \t\t\t\t\t"ID" : 11, (esc)
  \t\t\t\t\t"NUM_BASES_A" : 27, (esc)
  \t\t\t\t\t"NUM_BASES_C" : 28, (esc)
  \t\t\t\t\t"NUM_BASES_G" : 22, (esc)
  \t\t\t\t\t"NUM_BASES_T" : 19, (esc)
  \t\t\t\t\t"NUM_FRAMES" : 4096, (esc)
  \t\t\t\t\t"NUM_HALF_SANDWICHES" : 0, (esc)
  \t\t\t\t\t"NUM_PULSES" : 98, (esc)
  \t\t\t\t\t"NUM_PULSE_LABEL_STUTTERS" : 0, (esc)
  \t\t\t\t\t"NUM_SANDWICHES" : 0, (esc)
  \t\t\t\t\t"PIXEL_CHECKSUM" : 0, (esc)
  \t\t\t\t\t"PKMAX_A" : 0, (esc)
  \t\t\t\t\t"PKMAX_C" : 0, (esc)
  \t\t\t\t\t"PKMAX_G" : 0, (esc)
  \t\t\t\t\t"PKMAX_T" : 0, (esc)
  \t\t\t\t\t"PKMID_A" : 229.375, (esc)
  \t\t\t\t\t"PKMID_C" : 155.875, (esc)
  \t\t\t\t\t"PKMID_FRAMES_A" : 554, (esc)
  \t\t\t\t\t"PKMID_FRAMES_C" : 543, (esc)
  \t\t\t\t\t"PKMID_FRAMES_G" : 321, (esc)
  \t\t\t\t\t"PKMID_FRAMES_T" : 298, (esc)
  \t\t\t\t\t"PKMID_G" : 99.875, (esc)
  \t\t\t\t\t"PKMID_T" : 62.78125, (esc)
  \t\t\t\t\t"PKZVAR_A" : 0, (esc)
  \t\t\t\t\t"PKZVAR_C" : 0, (esc)
  \t\t\t\t\t"PKZVAR_G" : 0, (esc)
  \t\t\t\t\t"PKZVAR_T" : 0, (esc)
  \t\t\t\t\t"PULSE_DETECTION_SCORE" : 0, (esc)
  \t\t\t\t\t"PULSE_WIDTH" : 1912, (esc)
  \t\t\t\t\t"TRACE_AUTOCORR" : 0 (esc)
  \t\t\t\t}, (esc)
  \t\t\t\t{ (esc)
  \t\t\t\t\t"BASELINE_MEAN" : 0.6552734375, (esc)
  \t\t\t\t\t"BASELINE_SD" : 20.875, (esc)
  \t\t\t\t\t"BASE_WIDTH" : 1925, (esc)
  \t\t\t\t\t"BPZVAR_A" : 0, (esc)
  \t\t\t\t\t"BPZVAR_C" : 0, (esc)
  \t\t\t\t\t"BPZVAR_G" : 0, (esc)
  \t\t\t\t\t"BPZVAR_T" : 0, (esc)
  \t\t\t\t\t"DME_STATUS" : 0, (esc)
  \t\t\t\t\t"ID" : 12, (esc)
  \t\t\t\t\t"NUM_BASES_A" : 30, (esc)
  \t\t\t\t\t"NUM_BASES_C" : 32, (esc)
  \t\t\t\t\t"NUM_BASES_G" : 24, (esc)
  \t\t\t\t\t"NUM_BASES_T" : 15, (esc)
  \t\t\t\t\t"NUM_FRAMES" : 4096, (esc)
  \t\t\t\t\t"NUM_HALF_SANDWICHES" : 0, (esc)
  \t\t\t\t\t"NUM_PULSES" : 101, (esc)
  \t\t\t\t\t"NUM_PULSE_LABEL_STUTTERS" : 0, (esc)
  \t\t\t\t\t"NUM_SANDWICHES" : 0, (esc)
  \t\t\t\t\t"PIXEL_CHECKSUM" : 0, (esc)
  \t\t\t\t\t"PKMAX_A" : 0, (esc)
  \t\t\t\t\t"PKMAX_C" : 0, (esc)
  \t\t\t\t\t"PKMAX_G" : 0, (esc)
  \t\t\t\t\t"PKMAX_T" : 0, (esc)
  \t\t\t\t\t"PKMID_A" : 230, (esc)
  \t\t\t\t\t"PKMID_C" : 157.625, (esc)
  \t\t\t\t\t"PKMID_FRAMES_A" : 525, (esc)
  \t\t\t\t\t"PKMID_FRAMES_C" : 426, (esc)
  \t\t\t\t\t"PKMID_FRAMES_G" : 387, (esc)
  \t\t\t\t\t"PKMID_FRAMES_T" : 386, (esc)
  \t\t\t\t\t"PKMID_G" : 100.9375, (esc)
  \t\t\t\t\t"PKMID_T" : 62.25, (esc)
  \t\t\t\t\t"PKZVAR_A" : 0, (esc)
  \t\t\t\t\t"PKZVAR_C" : 0, (esc)
  \t\t\t\t\t"PKZVAR_G" : 0, (esc)
  \t\t\t\t\t"PKZVAR_T" : 0, (esc)
  \t\t\t\t\t"PULSE_DETECTION_SCORE" : 0, (esc)
  \t\t\t\t\t"PULSE_WIDTH" : 1925, (esc)
  \t\t\t\t\t"TRACE_AUTOCORR" : 0 (esc)
  \t\t\t\t}, (esc)
  \t\t\t\t{ (esc)
  \t\t\t\t\t"BASELINE_MEAN" : 0.8564453125, (esc)
  \t\t\t\t\t"BASELINE_SD" : 21.71875, (esc)
  \t\t\t\t\t"BASE_WIDTH" : 1908, (esc)
  \t\t\t\t\t"BPZVAR_A" : 0, (esc)
  \t\t\t\t\t"BPZVAR_C" : 0, (esc)
  \t\t\t\t\t"BPZVAR_G" : 0, (esc)
  \t\t\t\t\t"BPZVAR_T" : 0, (esc)
  \t\t\t\t\t"DME_STATUS" : 0, (esc)
  \t\t\t\t\t"ID" : 13, (esc)
  \t\t\t\t\t"NUM_BASES_A" : 27, (esc)
  \t\t\t\t\t"NUM_BASES_C" : 28, (esc)
  \t\t\t\t\t"NUM_BASES_G" : 22, (esc)
  \t\t\t\t\t"NUM_BASES_T" : 19, (esc)
  \t\t\t\t\t"NUM_FRAMES" : 4096, (esc)
  \t\t\t\t\t"NUM_HALF_SANDWICHES" : 0, (esc)
  \t\t\t\t\t"NUM_PULSES" : 98, (esc)
  \t\t\t\t\t"NUM_PULSE_LABEL_STUTTERS" : 0, (esc)
  \t\t\t\t\t"NUM_SANDWICHES" : 0, (esc)
  \t\t\t\t\t"PIXEL_CHECKSUM" : 0, (esc)
  \t\t\t\t\t"PKMAX_A" : 0, (esc)
  \t\t\t\t\t"PKMAX_C" : 0, (esc)
  \t\t\t\t\t"PKMAX_G" : 0, (esc)
  \t\t\t\t\t"PKMAX_T" : 0, (esc)
  \t\t\t\t\t"PKMID_A" : 229.375, (esc)
  \t\t\t\t\t"PKMID_C" : 155.875, (esc)
  \t\t\t\t\t"PKMID_FRAMES_A" : 554, (esc)
  \t\t\t\t\t"PKMID_FRAMES_C" : 543, (esc)
  \t\t\t\t\t"PKMID_FRAMES_G" : 321, (esc)
  \t\t\t\t\t"PKMID_FRAMES_T" : 298, (esc)
  \t\t\t\t\t"PKMID_G" : 99.875, (esc)
  \t\t\t\t\t"PKMID_T" : 62.78125, (esc)
  \t\t\t\t\t"PKZVAR_A" : 0, (esc)
  \t\t\t\t\t"PKZVAR_C" : 0, (esc)
  \t\t\t\t\t"PKZVAR_G" : 0, (esc)
  \t\t\t\t\t"PKZVAR_T" : 0, (esc)
  \t\t\t\t\t"PULSE_DETECTION_SCORE" : 0, (esc)
  \t\t\t\t\t"PULSE_WIDTH" : 1912, (esc)
  \t\t\t\t\t"TRACE_AUTOCORR" : 0 (esc)
  \t\t\t\t} (esc)
  \t\t\t], (esc)
  \t\t\t"ZMW_ID" : 1, (esc)
  \t\t\t"ZMW_NUMBER" : 1 (esc)
  \t\t} (esc)
  \t], (esc)
  \t"TYPE" : "BAZ_OVERVIEW" (esc)
  }

  $ bazviewer --silent -m -i2 ${BAZFILE} 
  {
  \t"METRICS" :  (esc)
  \t[ (esc)
  \t\t{ (esc)
  \t\t\t"INTERNAL" : false, (esc)
  \t\t\t"METRICS" :  (esc)
  \t\t\t[ (esc)
  \t\t\t\t{ (esc)
  \t\t\t\t\t"BASELINE_MEAN" : 0.23583984375, (esc)
  \t\t\t\t\t"BASELINE_SD" : 6.09375, (esc)
  \t\t\t\t\t"BASE_WIDTH" : 2075, (esc)
  \t\t\t\t\t"BPZVAR_A" : 0, (esc)
  \t\t\t\t\t"BPZVAR_C" : 0, (esc)
  \t\t\t\t\t"BPZVAR_G" : 0, (esc)
  \t\t\t\t\t"BPZVAR_T" : 0, (esc)
  \t\t\t\t\t"DME_STATUS" : 0, (esc)
  \t\t\t\t\t"ID" : 0, (esc)
  \t\t\t\t\t"NUM_BASES_A" : 20, (esc)
  \t\t\t\t\t"NUM_BASES_C" : 20, (esc)
  \t\t\t\t\t"NUM_BASES_G" : 23, (esc)
  \t\t\t\t\t"NUM_BASES_T" : 34, (esc)
  \t\t\t\t\t"NUM_FRAMES" : 4608, (esc)
  \t\t\t\t\t"NUM_HALF_SANDWICHES" : 0, (esc)
  \t\t\t\t\t"NUM_PULSES" : 99, (esc)
  \t\t\t\t\t"NUM_PULSE_LABEL_STUTTERS" : 0, (esc)
  \t\t\t\t\t"NUM_SANDWICHES" : 0, (esc)
  \t\t\t\t\t"PIXEL_CHECKSUM" : 0, (esc)
  \t\t\t\t\t"PKMAX_A" : 0, (esc)
  \t\t\t\t\t"PKMAX_C" : 0, (esc)
  \t\t\t\t\t"PKMAX_G" : 0, (esc)
  \t\t\t\t\t"PKMAX_T" : 0, (esc)
  \t\t\t\t\t"PKMID_A" : 228.5, (esc)
  \t\t\t\t\t"PKMID_C" : 156.375, (esc)
  \t\t\t\t\t"PKMID_FRAMES_A" : 631, (esc)
  \t\t\t\t\t"PKMID_FRAMES_C" : 325, (esc)
  \t\t\t\t\t"PKMID_FRAMES_G" : 393, (esc)
  \t\t\t\t\t"PKMID_FRAMES_T" : 532, (esc)
  \t\t\t\t\t"PKMID_G" : 100.3125, (esc)
  \t\t\t\t\t"PKMID_T" : 62.40625, (esc)
  \t\t\t\t\t"PKZVAR_A" : 0, (esc)
  \t\t\t\t\t"PKZVAR_C" : 0, (esc)
  \t\t\t\t\t"PKZVAR_G" : 0, (esc)
  \t\t\t\t\t"PKZVAR_T" : 0, (esc)
  \t\t\t\t\t"PULSE_DETECTION_SCORE" : 0, (esc)
  \t\t\t\t\t"PULSE_WIDTH" : 2079, (esc)
  \t\t\t\t\t"TRACE_AUTOCORR" : 0 (esc)
  \t\t\t\t}, (esc)
  \t\t\t\t{ (esc)
  \t\t\t\t\t"BASELINE_MEAN" : 2.974609375, (esc)
  \t\t\t\t\t"BASELINE_SD" : 16.375, (esc)
  \t\t\t\t\t"BASE_WIDTH" : 21858, (esc)
  \t\t\t\t\t"BPZVAR_A" : 0, (esc)
  \t\t\t\t\t"BPZVAR_C" : 0, (esc)
  \t\t\t\t\t"BPZVAR_G" : 0, (esc)
  \t\t\t\t\t"BPZVAR_T" : 0, (esc)
  \t\t\t\t\t"DME_STATUS" : 0, (esc)
  \t\t\t\t\t"ID" : 1, (esc)
  \t\t\t\t\t"NUM_BASES_A" : 186, (esc)
  \t\t\t\t\t"NUM_BASES_C" : 228, (esc)
  \t\t\t\t\t"NUM_BASES_G" : 276, (esc)
  \t\t\t\t\t"NUM_BASES_T" : 306, (esc)
  \t\t\t\t\t"NUM_FRAMES" : 49152, (esc)
  \t\t\t\t\t"NUM_HALF_SANDWICHES" : 0, (esc)
  \t\t\t\t\t"NUM_PULSES" : 1014, (esc)
  \t\t\t\t\t"NUM_PULSE_LABEL_STUTTERS" : 0, (esc)
  \t\t\t\t\t"NUM_SANDWICHES" : 0, (esc)
  \t\t\t\t\t"PIXEL_CHECKSUM" : 0, (esc)
  \t\t\t\t\t"PKMAX_A" : 0, (esc)
  \t\t\t\t\t"PKMAX_C" : 0, (esc)
  \t\t\t\t\t"PKMAX_G" : 0, (esc)
  \t\t\t\t\t"PKMAX_T" : 0, (esc)
  \t\t\t\t\t"PKMID_A" : 230.125, (esc)
  \t\t\t\t\t"PKMID_C" : 156.625, (esc)
  \t\t\t\t\t"PKMID_FRAMES_A" : 5580, (esc)
  \t\t\t\t\t"PKMID_FRAMES_C" : 3936, (esc)
  \t\t\t\t\t"PKMID_FRAMES_G" : 5280, (esc)
  \t\t\t\t\t"PKMID_FRAMES_T" : 5070, (esc)
  \t\t\t\t\t"PKMID_G" : 99.625, (esc)
  \t\t\t\t\t"PKMID_T" : 62.6875, (esc)
  \t\t\t\t\t"PKZVAR_A" : 0, (esc)
  \t\t\t\t\t"PKZVAR_C" : 0, (esc)
  \t\t\t\t\t"PKZVAR_G" : 0, (esc)
  \t\t\t\t\t"PKZVAR_T" : 0, (esc)
  \t\t\t\t\t"PULSE_DETECTION_SCORE" : 0, (esc)
  \t\t\t\t\t"PULSE_WIDTH" : 21894, (esc)
  \t\t\t\t\t"TRACE_AUTOCORR" : 0 (esc)
  \t\t\t\t} (esc)
  \t\t\t], (esc)
  \t\t\t"ZMW_ID" : 2, (esc)
  \t\t\t"ZMW_NUMBER" : 2 (esc)
  \t\t} (esc)
  \t], (esc)
  \t"TYPE" : "BAZ_OVERVIEW" (esc)
  }



# Generate complete metrics by disabling preHQ algorithm.
  $ smrt-basecaller --config source.TraceReplication='{"numFrames":16384, "numZmwLanes":4,"traceFile":"'$TRCFILE'" }' \
  > --config multipleBazFiles=false --config layout.lanesPerPool=1 --config=algorithm.modelEstimationMode=FixedEstimations  \
  > --outputbazfile ${BAZFILE} > /dev/null

  $ bazviewer --silent -m -f ${BAZFILE}
  {
  \t"METRICS" :  (esc)
  \t[ (esc)
  \t\t{ (esc)
  \t\t\t"INTERNAL" : false, (esc)
  \t\t\t"METRICS" :  (esc)
  \t\t\t[ (esc)
  \t\t\t\t{ (esc)
  \t\t\t\t\t"BASELINE_MEAN" : 0.63818359375, (esc)
  \t\t\t\t\t"BASELINE_SD" : 5.8359375, (esc)
  \t\t\t\t\t"BASE_WIDTH" : 215, (esc)
  \t\t\t\t\t"BPZVAR_A" : 0, (esc)
  \t\t\t\t\t"BPZVAR_C" : 0, (esc)
  \t\t\t\t\t"BPZVAR_G" : 0, (esc)
  \t\t\t\t\t"BPZVAR_T" : 0, (esc)
  \t\t\t\t\t"DME_STATUS" : 0, (esc)
  \t\t\t\t\t"ID" : 0, (esc)
  \t\t\t\t\t"NUM_BASES_A" : 4, (esc)
  \t\t\t\t\t"NUM_BASES_C" : 3, (esc)
  \t\t\t\t\t"NUM_BASES_G" : 4, (esc)
  \t\t\t\t\t"NUM_BASES_T" : 2, (esc)
  \t\t\t\t\t"NUM_FRAMES" : 512, (esc)
  \t\t\t\t\t"NUM_HALF_SANDWICHES" : 0, (esc)
  \t\t\t\t\t"NUM_PULSES" : 13, (esc)
  \t\t\t\t\t"NUM_PULSE_LABEL_STUTTERS" : 0, (esc)
  \t\t\t\t\t"NUM_SANDWICHES" : 0, (esc)
  \t\t\t\t\t"PIXEL_CHECKSUM" : 0, (esc)
  \t\t\t\t\t"PKMAX_A" : 0, (esc)
  \t\t\t\t\t"PKMAX_C" : 0, (esc)
  \t\t\t\t\t"PKMAX_G" : 0, (esc)
  \t\t\t\t\t"PKMAX_T" : 0, (esc)
  \t\t\t\t\t"PKMID_A" : 233.25, (esc)
  \t\t\t\t\t"PKMID_C" : 156.125, (esc)
  \t\t\t\t\t"PKMID_FRAMES_A" : 60, (esc)
  \t\t\t\t\t"PKMID_FRAMES_C" : 36, (esc)
  \t\t\t\t\t"PKMID_FRAMES_G" : 73, (esc)
  \t\t\t\t\t"PKMID_FRAMES_T" : 20, (esc)
  \t\t\t\t\t"PKMID_G" : 95.6875, (esc)
  \t\t\t\t\t"PKMID_T" : 59.53125, (esc)
  \t\t\t\t\t"PKZVAR_A" : 0, (esc)
  \t\t\t\t\t"PKZVAR_C" : 0, (esc)
  \t\t\t\t\t"PKZVAR_G" : 0, (esc)
  \t\t\t\t\t"PKZVAR_T" : 0, (esc)
  \t\t\t\t\t"PULSE_DETECTION_SCORE" : 0, (esc)
  \t\t\t\t\t"PULSE_WIDTH" : 215, (esc)
  \t\t\t\t\t"TRACE_AUTOCORR" : 0 (esc)
  \t\t\t\t}, (esc)
  \t\t\t\t{ (esc)
  \t\t\t\t\t"BASELINE_MEAN" : -0.450439453125, (esc)
  \t\t\t\t\t"BASELINE_SD" : 5.859375, (esc)
  \t\t\t\t\t"BASE_WIDTH" : 2002, (esc)
  \t\t\t\t\t"BPZVAR_A" : 0, (esc)
  \t\t\t\t\t"BPZVAR_C" : 0, (esc)
  \t\t\t\t\t"BPZVAR_G" : 0, (esc)
  \t\t\t\t\t"BPZVAR_T" : 0, (esc)
  \t\t\t\t\t"DME_STATUS" : 0, (esc)
  \t\t\t\t\t"ID" : 1, (esc)
  \t\t\t\t\t"NUM_BASES_A" : 23, (esc)
  \t\t\t\t\t"NUM_BASES_C" : 24, (esc)
  \t\t\t\t\t"NUM_BASES_G" : 20, (esc)
  \t\t\t\t\t"NUM_BASES_T" : 33, (esc)
  \t\t\t\t\t"NUM_FRAMES" : 4096, (esc)
  \t\t\t\t\t"NUM_HALF_SANDWICHES" : 0, (esc)
  \t\t\t\t\t"NUM_PULSES" : 101, (esc)
  \t\t\t\t\t"NUM_PULSE_LABEL_STUTTERS" : 0, (esc)
  \t\t\t\t\t"NUM_SANDWICHES" : 0, (esc)
  \t\t\t\t\t"PIXEL_CHECKSUM" : 0, (esc)
  \t\t\t\t\t"PKMAX_A" : 0, (esc)
  \t\t\t\t\t"PKMAX_C" : 0, (esc)
  \t\t\t\t\t"PKMAX_G" : 0, (esc)
  \t\t\t\t\t"PKMAX_T" : 0, (esc)
  \t\t\t\t\t"PKMID_A" : 225.875, (esc)
  \t\t\t\t\t"PKMID_C" : 157.125, (esc)
  \t\t\t\t\t"PKMID_FRAMES_A" : 472, (esc)
  \t\t\t\t\t"PKMID_FRAMES_C" : 407, (esc)
  \t\t\t\t\t"PKMID_FRAMES_G" : 290, (esc)
  \t\t\t\t\t"PKMID_FRAMES_T" : 633, (esc)
  \t\t\t\t\t"PKMID_G" : 98.6875, (esc)
  \t\t\t\t\t"PKMID_T" : 62.09375, (esc)
  \t\t\t\t\t"PKZVAR_A" : 0, (esc)
  \t\t\t\t\t"PKZVAR_C" : 0, (esc)
  \t\t\t\t\t"PKZVAR_G" : 0, (esc)
  \t\t\t\t\t"PKZVAR_T" : 0, (esc)
  \t\t\t\t\t"PULSE_DETECTION_SCORE" : 0, (esc)
  \t\t\t\t\t"PULSE_WIDTH" : 2004, (esc)
  \t\t\t\t\t"TRACE_AUTOCORR" : 0 (esc)
  \t\t\t\t}, (esc)
  \t\t\t\t{ (esc)
  \t\t\t\t\t"BASELINE_MEAN" : -0.6513671875, (esc)
  \t\t\t\t\t"BASELINE_SD" : 7.4921875, (esc)
  \t\t\t\t\t"BASE_WIDTH" : 2040, (esc)
  \t\t\t\t\t"BPZVAR_A" : 0, (esc)
  \t\t\t\t\t"BPZVAR_C" : 0, (esc)
  \t\t\t\t\t"BPZVAR_G" : 0, (esc)
  \t\t\t\t\t"BPZVAR_T" : 0, (esc)
  \t\t\t\t\t"DME_STATUS" : 0, (esc)
  \t\t\t\t\t"ID" : 2, (esc)
  \t\t\t\t\t"NUM_BASES_A" : 25, (esc)
  \t\t\t\t\t"NUM_BASES_C" : 25, (esc)
  \t\t\t\t\t"NUM_BASES_G" : 28, (esc)
  \t\t\t\t\t"NUM_BASES_T" : 22, (esc)
  \t\t\t\t\t"NUM_FRAMES" : 4096, (esc)
  \t\t\t\t\t"NUM_HALF_SANDWICHES" : 0, (esc)
  \t\t\t\t\t"NUM_PULSES" : 100, (esc)
  \t\t\t\t\t"NUM_PULSE_LABEL_STUTTERS" : 0, (esc)
  \t\t\t\t\t"NUM_SANDWICHES" : 0, (esc)
  \t\t\t\t\t"PIXEL_CHECKSUM" : 0, (esc)
  \t\t\t\t\t"PKMAX_A" : 0, (esc)
  \t\t\t\t\t"PKMAX_C" : 0, (esc)
  \t\t\t\t\t"PKMAX_G" : 0, (esc)
  \t\t\t\t\t"PKMAX_T" : 0, (esc)
  \t\t\t\t\t"PKMID_A" : 229.5, (esc)
  \t\t\t\t\t"PKMID_C" : 157.125, (esc)
  \t\t\t\t\t"PKMID_FRAMES_A" : 449, (esc)
  \t\t\t\t\t"PKMID_FRAMES_C" : 361, (esc)
  \t\t\t\t\t"PKMID_FRAMES_G" : 469, (esc)
  \t\t\t\t\t"PKMID_FRAMES_T" : 561, (esc)
  \t\t\t\t\t"PKMID_G" : 98.9375, (esc)
  \t\t\t\t\t"PKMID_T" : 62, (esc)
  \t\t\t\t\t"PKZVAR_A" : 0, (esc)
  \t\t\t\t\t"PKZVAR_C" : 0, (esc)
  \t\t\t\t\t"PKZVAR_G" : 0, (esc)
  \t\t\t\t\t"PKZVAR_T" : 0, (esc)
  \t\t\t\t\t"PULSE_DETECTION_SCORE" : 0, (esc)
  \t\t\t\t\t"PULSE_WIDTH" : 2040, (esc)
  \t\t\t\t\t"TRACE_AUTOCORR" : 0 (esc)
  \t\t\t\t}, (esc)
  \t\t\t\t{ (esc)
  \t\t\t\t\t"BASELINE_MEAN" : -0.54931640625, (esc)
  \t\t\t\t\t"BASELINE_SD" : 9.53125, (esc)
  \t\t\t\t\t"BASE_WIDTH" : 2003, (esc)
  \t\t\t\t\t"BPZVAR_A" : 0, (esc)
  \t\t\t\t\t"BPZVAR_C" : 0, (esc)
  \t\t\t\t\t"BPZVAR_G" : 0, (esc)
  \t\t\t\t\t"BPZVAR_T" : 0, (esc)
  \t\t\t\t\t"DME_STATUS" : 0, (esc)
  \t\t\t\t\t"ID" : 3, (esc)
  \t\t\t\t\t"NUM_BASES_A" : 23, (esc)
  \t\t\t\t\t"NUM_BASES_C" : 24, (esc)
  \t\t\t\t\t"NUM_BASES_G" : 20, (esc)
  \t\t\t\t\t"NUM_BASES_T" : 33, (esc)
  \t\t\t\t\t"NUM_FRAMES" : 4096, (esc)
  \t\t\t\t\t"NUM_HALF_SANDWICHES" : 0, (esc)
  \t\t\t\t\t"NUM_PULSES" : 101, (esc)
  \t\t\t\t\t"NUM_PULSE_LABEL_STUTTERS" : 0, (esc)
  \t\t\t\t\t"NUM_SANDWICHES" : 0, (esc)
  \t\t\t\t\t"PIXEL_CHECKSUM" : 0, (esc)
  \t\t\t\t\t"PKMAX_A" : 0, (esc)
  \t\t\t\t\t"PKMAX_C" : 0, (esc)
  \t\t\t\t\t"PKMAX_G" : 0, (esc)
  \t\t\t\t\t"PKMAX_T" : 0, (esc)
  \t\t\t\t\t"PKMID_A" : 226, (esc)
  \t\t\t\t\t"PKMID_C" : 157.25, (esc)
  \t\t\t\t\t"PKMID_FRAMES_A" : 472, (esc)
  \t\t\t\t\t"PKMID_FRAMES_C" : 407, (esc)
  \t\t\t\t\t"PKMID_FRAMES_G" : 290, (esc)
  \t\t\t\t\t"PKMID_FRAMES_T" : 634, (esc)
  \t\t\t\t\t"PKMID_G" : 98.6875, (esc)
  \t\t\t\t\t"PKMID_T" : 62.15625, (esc)
  \t\t\t\t\t"PKZVAR_A" : 0, (esc)
  \t\t\t\t\t"PKZVAR_C" : 0, (esc)
  \t\t\t\t\t"PKZVAR_G" : 0, (esc)
  \t\t\t\t\t"PKZVAR_T" : 0, (esc)
  \t\t\t\t\t"PULSE_DETECTION_SCORE" : 0, (esc)
  \t\t\t\t\t"PULSE_WIDTH" : 2005, (esc)
  \t\t\t\t\t"TRACE_AUTOCORR" : 0 (esc)
  \t\t\t\t} (esc)
  \t\t\t], (esc)
  \t\t\t"ZMW_ID" : 0, (esc)
  \t\t\t"ZMW_NUMBER" : 0 (esc)
  \t\t} (esc)
  \t], (esc)
  \t"TYPE" : "BAZ_OVERVIEW" (esc)
  }
