  $ BAZFILE=${CRAMTMP}/designer.baz
  $ TRCFILE=/pbi/dept/primary/sim/mongo/test_designer_mongo_acgt_SNR-40.trc.h5

  $ smrt-basecaller --numZmwLanes 64 --config layout.lanesPerPool=16 --frames=1024 --config=algorithm.modelEstimationMode=FixedEstimations --inputfile ${TRCFILE} --outputbazfile ${BAZFILE} > /dev/null

  $ bazviewer --silent -l ${BAZFILE} | tail -n +1 | wc -l
  4097

  $ ${TESTDIR}/verify_designer_zmw.sh $BAZFILE $TRCFILE 0 ${CRAMTMP}/designer_zmw_0.txt ${CRAMTMP}/exp_designer_zmw_0.txt
  AAAAGGGTTTCCCGTACGTACGTACGTACGTAC
  -AAAGGGTTTCCCGTACGTACGTACGTACGTAC

  $ ${TESTDIR}/verify_designer_zmw.sh $BAZFILE $TRCFILE 10 ${CRAMTMP}/designer_zmw_10.txt ${CRAMTMP}/exp_designer_zmw_10.txt
  AAAAGGGTTTCCCGTACGTACGTACGTACGACT
  -AAAGGGTTTCCCGTACGTACGTACGTACGACT

  $ ${TESTDIR}/verify_designer_zmw.sh $BAZFILE $TRCFILE 100 ${CRAMTMP}/designer_zmw_100.txt ${CRAMTMP}/exp_designer_zmw_100.txt
  AAAAGGGTTTCCCGTACGTACGTACGTAGTGTC
  -AAAGGGTTTCCCGTACGTACGTACGTAGTGTC

  $ ${TESTDIR}/verify_designer_zmw.sh $BAZFILE $TRCFILE 1000 ${CRAMTMP}/designer_zmw_1000.txt ${CRAMTMP}/exp_designer_zmw_1000.txt
  AAAAGGGTTTCCCGTACGTACGTACGAGTCGTC
  -AAAGGGTTTCCCGTACGTACGTACGAGTCGTC

  $ BAZFILE=${CRAMTMP}/test4.baz
  $ TRCFILE=/pbi/dept/primary/sim/mongo/test4_mongo_acgt_SNR-40.trc.h5
  $ smrt-basecaller --numZmwLanes 4 --config layout.lanesPerPool=1 --frames=8192 --config=algorithm.modelEstimationMode=FixedEstimations --inputfile ${TRCFILE} --outputbazfile ${BAZFILE} > /dev/null

  $ bazviewer --silent -l ${BAZFILE} | tail -n +1 | wc -l
  257

  $ ${TESTDIR}/verify_align_zmw.sh $BAZFILE $TRCFILE 0 ${CRAMTMP}/align_zmw_0.txt ${CRAMTMP}/expected_align_zmw_0.txt
  -CACATTACCACTGTACTAATCGTTCTTGAACGAGAATATCTCAACCCCATTCTCTCCTTTGATGGTGTCGAAGCAGTGTATTGCTAGTGTGTTGCCCGTTGACGAGTTTGCCGA-TGCTTGCCTGTCATCACGTATGAATACGACTCGGAAAGGGGGCC-TTGGTACTGCATACACCCGACGAGTAATAC-
  CCACATTAACACTGTACTAATCGTTCTTGAACGAGAATATCTCAACCCCATTCTCTCCTGTGATGGTGTCGAAGCAGTGTATTGCTACTGTGTTGCCCGTTGACGAGTTTGCCGATTGCTTGCCTGTCATCACGTATGAATACGACTCGGAAAGGGGGCCGTTGGTACTGCATACACCCGACGACTAATACG

  $ ${TESTDIR}/verify_align_zmw.sh $BAZFILE $TRCFILE 64 ${CRAMTMP}/align_zmw_64.txt ${CRAMTMP}/expected_align_zmw_64.txt
  -TTGTAATACGCGCCCACACATAGCGTGGCGCGCATCCAGTA-CCAGGGACGGCTCGTCGCGCAATTGCTTCACGAGGGTCAG-CCCAAAACGGTCCATTGGTAAGGTGGTTTCATTATCCCTCGCTTTTACATCTCTCACCGGATGCAAGCTTACCTCATGCGAGATTGTG-A-
  GTTCTAATACGCGCCCACACATAGCCTGGCGCGCATCCAGTACCCAGGGACGGCTGGTCGCGCAATTGCTTCACGAGGGTCAGCCCCAAAACGGTCCATTGGTAAGGTGGTTTCAGTATCCCTCGCTTTTACAGCTCTCACCGTATGCAAGCTTACCTCATGCGAGATTGTGAAC

  $ ${TESTDIR}/verify_align_zmw.sh $BAZFILE $TRCFILE 160 ${CRAMTMP}/align_zmw_160.txt ${CRAMTMP}/expected_align_zmw_160.txt
  -ATTATGAGACGGCATAAGTCCAAATCAATGCTCCACCCGAAAAACAGGGTTTGCTTAACGCCAGTAAGACCAGGTGGTACCTCTGCCGTCTGCCTTAGATTGAGGATCGAAGCCCAACACGATCGTCTGGTC-TTTGCGTTGCGTGATACAAGGGTGCAGGGTTCTACATGTCCCTT-GG
  AATTATGAGACGGCATAAGTCCAAATCAATGCTCCACCCGAAAAACAGGGTTTGCTTAACGCCAGTAAGACCAGGTGGTACCTCTGCCGTCTGCCTTAGATTGAGGATCGAAGCCCAACACGATCGTCTGGTCTTTTGCGTGGCGTGATACAAGGGTGGAGGGTTCTACATGTCCCTTGGG

  $ ${TESTDIR}/verify_align_zmw.sh $BAZFILE $TRCFILE 255 ${CRAMTMP}/align_zmw_255.txt ${CRAMTMP}/expected_align_zmw_255.txt
  -AAGTTGGTTTAGGGCGGACCCGCAGGTCGTGCTTATTCTAACGGCTGAGGGACTTCGAGTCCTCCATACTGAGTATATCTGTCTTGCAACC-GCAGCTAAATCGTAAATCAGCATGCCTGGCAATATACGACAGTC--CACCGTATCGAGTATGCTCTAGGAACGCACACGGGTCGCACACAGAGCAA-AGGGC
  CAAGTTGGTTTAGGGCGGACCCGCAGGTAGTGCTTATTCGAACGGCTGAGGGACTTCGAGTCCTCCATACTGAGTATATCTGTCTTGCAACCTGCAGCTAAATCGTAAATCAGCATGCCTGGCAATATACCACAGTCGACACCGTATCGAGTATGCTCTAGGAACGCAAACGGGTCGCACACAGAGCAACAGGGC

  $ BAZFILE=${CRAMTMP}/test4_hfmetrics.baz
  $ smrt-basecaller --numZmwLanes 4 --config algorithm.Metrics.Method=Host --config layout.lanesPerPool=1 --frames=8192 --config=algorithm.modelEstimationMode=FixedEstimations --inputfile ${TRCFILE} --outputbazfile ${BAZFILE} > /dev/null

  $ ${TESTDIR}/verify_align_zmw.sh $BAZFILE $TRCFILE 4 ${CRAMTMP}/align_zmw_4.txt ${CRAMTMP}/expected_align_zmw_4.txt
  -CGGTAGAAGTGTACGGCTCTGACATAATGAGCCAGGCCGGTAGGCCGTCTTACACCCCTAGACGAGGTAGGTGTGACAAATAACGTGCCTCACAAGTCCGCTTTGTGTCGAGGTAAGAAGCTAAATAGGCCTGGTCTGTAGAGGCAGACGTTCGGTGCAACGGGACA-TCA
  CCGGTAGAAGTGTACGGCTCTGACATAATGAGCCAGGCCGGTAGGCCGTCTTACACCCCTAGACGAGGTAGGTGTGACAAATAACCTGCCTCACAAGTCCGCTTTGTGTCGAGGTAAGAAGCTAAATAGGCCTGGTCTGTAGAGGCAGACGTTCGGTGCAACGGGACATTCA

  $ ${TESTDIR}/verify_align_zmw.sh $BAZFILE $TRCFILE 18 ${CRAMTMP}/align_zmw_18.txt ${CRAMTMP}/expected_align_zmw_18.txt
  -TCCATGACCTCATAATCATTTAGGTTAATGCACGCCCGGATCAAGTTAGGACCTACACCAGTGGAGGGCATGCTCATGCCTCGTGCGGGCGTATAGTGGACGTCGAAGGATCTCGGTACTACCAACTAGACAGATTGAGAAATTGATAGAATTGACACTCGCTCATT--
  TTCCATGACCTCATAATCATTTAGGTTAA-GCACGACCGGATCAAGTTAGGACCTACACCAGTGGAGGGCATGCTCATGCCTCGTGCGGGCGTATAGTGGACGTCGAAGGATCTCGCTACTACCAACTAGAAAGATTGAGAAATTGATAGAATTGACACTCGCTCATTCG
