  $ BAZFILE=${CRAMTMP}/designer.baz
  $ TRCFILE=/pbi/dept/primary/sim/mongo/test_designer_mongo_acgt_SNR-40.trc.h5

  $ smrt-basecaller --config source.TraceReplication='{"numFrames":1024, "numZmwLanes":64,"traceFile":"'$TRCFILE'" }' \
  > --config multipleBazFiles=false --config algorithm.Metrics.framesPerHFMetricBlock=512 --config layout.lanesPerPool=16   \
  > --config=algorithm.modelEstimationMode=FixedEstimations --outputbazfile ${BAZFILE} > /dev/null

  $ bazviewer --silent -l ${BAZFILE} | tail -n +1 | wc -l
  4097

  $ ${TESTDIR}/verify_designer_zmw.sh $BAZFILE $TRCFILE 0 ${CRAMTMP}/designer_zmw_0.txt ${CRAMTMP}/exp_designer_zmw_0.txt
  AAAAGGGTTTCCCGTACGTACGTACGTACGTAC
  -AAAGGGTTTCCCGTACGTACGTACGTACGTAC

  $ ${TESTDIR}/verify_designer_zmw.sh $BAZFILE $TRCFILE 10 ${CRAMTMP}/designer_zmw_10.txt ${CRAMTMP}/exp_designer_zmw_10.txt
  AAAAGGGTTTCCCGTACGTACGTACGTACGACT
  -AAAGGGTTTCCCGTACGTACGTACGTACGACT

  $ ${TESTDIR}/verify_designer_zmw.sh $BAZFILE $TRCFILE 100 ${CRAMTMP}/designer_zmw_100.txt ${CRAMTMP}/exp_designer_zmw_100.txt
  AAAAGGGTTTCCCGTACGTACGTACGTAGTGTC
  -AAAGGGTTTCCCGTACGTACGTACGTAGTGTC

  $ ${TESTDIR}/verify_designer_zmw.sh $BAZFILE $TRCFILE 1000 ${CRAMTMP}/designer_zmw_1000.txt ${CRAMTMP}/exp_designer_zmw_1000.txt
  AAAAGGGTTTCCCGTACGTACGTACGAGTCGTC
  -AAAGGGTTTCCCGTACGTACGTACGAGTCGTC

  $ BAZFILE=${CRAMTMP}/test4.baz
  $ TRCFILE=/pbi/dept/primary/sim/mongo/test4_mongo_acgt_SNR-40.trc.h5
  $ smrt-basecaller --config source.TraceReplication='{"numFrames":8192, "numZmwLanes":4,"traceFile":"'$TRCFILE'" }' \
  > --config multipleBazFiles=false --config layout.lanesPerPool=1 --config=algorithm.modelEstimationMode=FixedEstimations \
  > --outputbazfile ${BAZFILE} > /dev/null

  $ bazviewer --silent -l ${BAZFILE} | tail -n +1 | wc -l
  257

  $ ${TESTDIR}/verify_align_zmw.sh $BAZFILE $TRCFILE 0 ${CRAMTMP}/align_zmw_0.txt ${CRAMTMP}/expected_align_zmw_0.txt
  -CACATTACCACTGTACTAATCGTTCTTGAACGAGAATATCTCAACCCCATTCTCTCCT-TGATGGTGTCGAAGCAGTGTATTGCTAGTGTGTTGCCCGTTGACGAGTTTGCCGA-TGCTTGCCTGTCATCACGTATGAATACGACTCGGAAAGGGGGCC-TTGGTACTGCATACACCCGACGAGTAATAC-
  CCACATTAACACTGTACTAATCGTTCTTGAACGAGAATATCTCAACCCCATTCTCTCCTGTGATGGTGTCGAAGCAGTGTATTGCTACTGTGTTGCCCGTTGACGAGTTTGCCGATTGCTTGCCTGTCATCACGTATGAATACGACTCGGAAAGGGGGCCGTTGGTACTGCATACACCCGACGACTAATACG

  $ ${TESTDIR}/verify_align_zmw.sh $BAZFILE $TRCFILE 64 ${CRAMTMP}/align_zmw_64.txt ${CRAMTMP}/expected_align_zmw_64.txt
  -TTGTAATACGCGCCCACACATAGCGTGGCGCGCATCCAGTA-CCAGGGACGGCTCGTCGC-CAATTGCTTCACGAGGGTCAG-CCCAAAACGGTCCATTGGTAAGGTGGTTTCA-TATCCCTCGCTTTTACATCTCTCACCG-ATGCAAGCTTACCTCATGCGAGATTGTG-A-
  GTTCTAATACGCGCCCACACATAGCCTGGCGCGCATCCAGTACCCAGGGACGGCTGGTCGCGCAATTGCTTCACGAGGGTCAGCCCCAAAACGGTCCATTGGTAAGGTGGTTTCAGTATCCCTCGCTTTTACAGCTCTCACCGTATGCAAGCTTACCTCATGCGAGATTGTGAAC

  $ ${TESTDIR}/verify_align_zmw.sh $BAZFILE $TRCFILE 160 ${CRAMTMP}/align_zmw_160.txt ${CRAMTMP}/expected_align_zmw_160.txt
  -ATTATGAGACGGCATAAGTCCAAATCAATGCTCCACCCGAAAAACAGGG-TTGCTTAACGCCAGTAAGACCAGG-GGTACCTCTGCCGTCT-CCTTAGATTGAGGATCGAAGCCCAACACGATCGTCTGGTC-TTTGCGTTGCGTGATACAAGGGTGCAGGGTTCTACATGTCCC-T-GG
  AATTATGAGACGGCATAAGTCCAAATCAATGCTCCACCCGAAAAACAGGGTTTGCTTAACGCCAGTAAGACCAGGTGGTACCTCTGCCGTCTGCCTTAGATTGAGGATCGAAGCCCAACACGATCGTCTGGTCTTTTGCGTGGCGTGATACAAGGGTGGAGGGTTCTACATGTCCCTTGGG

  $ ${TESTDIR}/verify_align_zmw.sh $BAZFILE $TRCFILE 255 ${CRAMTMP}/align_zmw_255.txt ${CRAMTMP}/expected_align_zmw_255.txt
  -AAGTTGGTTTAGGGCGGACCCGCAGGTCGTGC-TATTC-AACGGCTGAGGGACTTCGAGTCCTCCATACTGAGTATATCTGTCTTGCAACC-GCAGCTAAATCGTAAATCAGCATGCCTGGCAATATACGACAGTC--CACCGTATCGAGTATGC-CTAGGAACGCACACGGGTCGCACACAGAGCAA-AGGGC
  CAAGTTGGTTTAGGGCGGACCCGCAGGTAGTGCTTATTCGAACGGCTGAGGGACTTCGAGTCCTCCATACTGAGTATATCTGTCTTGCAACCTGCAGCTAAATCGTAAATCAGCATGCCTGGCAATATACCACAGTCGACACCGTATCGAGTATGCTCTAGGAACGCAAACGGGTCGCACACAGAGCAACAGGGC

  $ BAZFILE=${CRAMTMP}/test4_hfmetrics.baz
  $ smrt-basecaller --config source.TraceReplication='{"numFrames":8192, "numZmwLanes":4,"traceFile":"'$TRCFILE'" }' \
  > --config multipleBazFiles=false --config algorithm.Metrics.Method=Host --config layout.lanesPerPool=1                  \
  > --config=algorithm.modelEstimationMode=FixedEstimations --outputbazfile ${BAZFILE} > /dev/null

  $ ${TESTDIR}/verify_align_zmw.sh $BAZFILE $TRCFILE 4 ${CRAMTMP}/align_zmw_4.txt ${CRAMTMP}/expected_align_zmw_4.txt
  -CGGTAGAAGTGTACGGCTCTGACATAATGAGCCAGGCCGGTAGGCCGTCTTACACCCCTAGACGAGGTAGGTGTGACAAATAACGTGCCTCACAA-TCCGC-TTGTGTCGAGGTAAGAAGCTAAATAGGCCTGGTCTGTAGAGGCAGACGTTC-GTGCAACGGGACA-TCA
  CCGGTAGAAGTGTACGGCTCTGACATAATGAGCCAGGCCGGTAGGCCGTCTTACACCCCTAGACGAGGTAGGTGTGACAAATAACCTGCCTCACAAGTCCGCTTTGTGTCGAGGTAAGAAGCTAAATAGGCCTGGTCTGTAGAGGCAGACGTTCGGTGCAACGGGACATTCA

  $ ${TESTDIR}/verify_align_zmw.sh $BAZFILE $TRCFILE 18 ${CRAMTMP}/align_zmw_18.txt ${CRAMTMP}/expected_align_zmw_18.txt
  -TCCATGACCTCATAATCATTTAGGTTAAGCACGCCCGGATCAAGTTAGGACCTACACCAGTGGAGGGCAT-CTCATGCCTCGTGCGGGCGTATAGTGGACGTCGAAGGATCTCGGTACTACCAACTAGACAGA-TGAGAAATTGATAGAATTGACACTCGCTCA-T--
  TTCCATGACCTCATAATCATTTAGGTTAAGCACGACCGGATCAAGTTAGGACCTACACCAGTGGAGGGCATGCTCATGCCTCGTGCGGGCGTATAGTGGACGTCGAAGGATCTCGCTACTACCAACTAGAAAGATTGAGAAATTGATAGAATTGACACTCGCTCATTCG
